name: delivery / docker

on:
  release:
    types:
      - released

env:
  BUILDER: "paketobuildpacks/builder:tiny"
  IMG_NAME: 'pack'
  USERNAME: 'buildpacksio'

jobs:
  deliver-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Determine version
        id: version
        shell: bash
        run: |
          echo "::set-output name=VERSION::$(echo ${{ github.event.release.tag_name }} | cut -d "v" -f2)"
      - name: Setup Working Dir
        shell: bash
        run: |
          cp .github/workflows/delivery/docker/buildpack.yml buildpack.yml
      - name: Fill buildpack.yml
        uses: cschleiden/replace-tokens@v1
        with:
          files: buildpack.yml
        env:
          PACK_VERSION: ${{ steps.version.outputs.VERSION }}
      - name: Determine App Name
        run: 'echo "::set-env name=IMG_NAME::$(echo ${USERNAME})/$(echo ${IMG_NAME})"'
      - name: Pack Build/Publish
        uses: dfreilich/pack-action@v1.0
        with:
          args: 'build ${{ env.IMG_NAME }}:${{ steps.version.outputs.VERSION }} --builder ${{ env.BUILDER }} --publish'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Tag Image as Latest
        run: |
          docker pull ${{ env.IMG_NAME }}:${{ steps.version.outputs.VERSION }}
          docker tag ${{ env.IMG_NAME }}:${{ steps.version.outputs.VERSION }} ${{ env.IMG_NAME }}:latest
          docker push ${{ env.IMG_NAME }}:latest
